# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-07 15:53
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_tournamentinfo_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentrounds',
            name='content',
            field=mezzanine.core.fields.RichTextField(default='Kucai', verbose_name='Content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournamentstandings',
            name='content',
            field=mezzanine.core.fields.RichTextField(default='Kucai', verbose_name='Content'),
            preserve_default=False,
        ),
    ]
